### ISSUE TITLE
ggvita::ggvita parameter trace_down_for_pruned incomplete

### ISSUE THREAD

**Issue by yangjr** [helloicyvodka/ggvita#1]
The pruned tips were trace down for their "Class", but not for their "Name". For example,

```
ggvita::ggvita(resDelta,1,trace_down_for_pruned=F) %++%
  geom_tippoint(aes(fill=I(tip.fill)),size=1,shape=21,color="NA") %++% 
  geom_tiplab(aes(label=Name),angle=90)

```
gives 
![image](https://user-images.githubusercontent.com/1413532/47400513-14331080-d770-11e8-98cb-e115c4c90141.png)

```
ggvita::ggvita(resDelta,1,trace_down_for_pruned=T) %++%
  geom_tippoint(aes(fill=I(tip.fill)),size=1,shape=21,color="NA") %++% 
  geom_tiplab(aes(label=Name),angle=90)
```
gives
![image](https://user-images.githubusercontent.com/1413532/47400550-3a58b080-d770-11e8-9d09-7d4bc94739fa.png)

**Comment by helloicyvodka** [comment]
I have debuged this issue. Thx!
